// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RpcClient is the client API for Rpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RpcClient interface {
	Exec(ctx context.Context, in *Json, opts ...grpc.CallOption) (*Json, error)
	Push(ctx context.Context, in *Json, opts ...grpc.CallOption) (Rpc_PushClient, error)
}

type rpcClient struct {
	cc grpc.ClientConnInterface
}

func NewRpcClient(cc grpc.ClientConnInterface) RpcClient {
	return &rpcClient{cc}
}

func (c *rpcClient) Exec(ctx context.Context, in *Json, opts ...grpc.CallOption) (*Json, error) {
	out := new(Json)
	err := c.cc.Invoke(ctx, "/pb.Rpc/Exec", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcClient) Push(ctx context.Context, in *Json, opts ...grpc.CallOption) (Rpc_PushClient, error) {
	stream, err := c.cc.NewStream(ctx, &Rpc_ServiceDesc.Streams[0], "/pb.Rpc/Push", opts...)
	if err != nil {
		return nil, err
	}
	x := &rpcPushClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Rpc_PushClient interface {
	Recv() (*Json, error)
	grpc.ClientStream
}

type rpcPushClient struct {
	grpc.ClientStream
}

func (x *rpcPushClient) Recv() (*Json, error) {
	m := new(Json)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RpcServer is the server API for Rpc service.
// All implementations must embed UnimplementedRpcServer
// for forward compatibility
type RpcServer interface {
	Exec(context.Context, *Json) (*Json, error)
	Push(*Json, Rpc_PushServer) error
	mustEmbedUnimplementedRpcServer()
}

// UnimplementedRpcServer must be embedded to have forward compatible implementations.
type UnimplementedRpcServer struct {
}

func (UnimplementedRpcServer) Exec(context.Context, *Json) (*Json, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedRpcServer) Push(*Json, Rpc_PushServer) error {
	return status.Errorf(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedRpcServer) mustEmbedUnimplementedRpcServer() {}

// UnsafeRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RpcServer will
// result in compilation errors.
type UnsafeRpcServer interface {
	mustEmbedUnimplementedRpcServer()
}

func RegisterRpcServer(s grpc.ServiceRegistrar, srv RpcServer) {
	s.RegisterService(&Rpc_ServiceDesc, srv)
}

func _Rpc_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Json)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Rpc/Exec",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServer).Exec(ctx, req.(*Json))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rpc_Push_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Json)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RpcServer).Push(m, &rpcPushServer{stream})
}

type Rpc_PushServer interface {
	Send(*Json) error
	grpc.ServerStream
}

type rpcPushServer struct {
	grpc.ServerStream
}

func (x *rpcPushServer) Send(m *Json) error {
	return x.ServerStream.SendMsg(m)
}

// Rpc_ServiceDesc is the grpc.ServiceDesc for Rpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Rpc",
	HandlerType: (*RpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Exec",
			Handler:    _Rpc_Exec_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Push",
			Handler:       _Rpc_Push_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "Rpc.proto",
}
